# -*- coding: utf-8 -*-
"""4889-안정적인_문자열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAN4uJj-d17x4HDMTnIFuMRTiRwk-aak
"""

cnt = 0
while True:
    ans = 0
    string = input()
    if '-' in string:
        break
    stack = list()
    cnt += 1
    for i in range(len(string)):
        if string[i] == '{':
            stack.append('{')
        else:
            if not stack:
                stack.append('{')
                ans += 1
            else :
                stack.pop()
    if stack:
        print(f'{cnt}. {ans+len(stack)//2}')
    else :
        print(f'{cnt}. {ans}')

{}